name: Run Python Script - Synthetic data generation 

on:
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python src/generate_data.py 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-output
          path: |
            dataset.csv
            new_dataset.csv
            comparison.png
